### ISSUE TITLE
uuid问题

### ISSUE THREAD

**Issue by wujx1992** [AXAET/iBeaconSDK2-example-iOS#1]
我这边只有使用demo里FDA50693-A4E2-4FB1-AFCF-C6EB07647825的uuid才能发现设备，并且发现出来的设备在demo中uuid都一样。如果使用设别真正的uuid反而一个设备都发现不了.
![img_2606](https://cloud.githubusercontent.com/assets/11516980/18034306/40bfdc20-6d6c-11e6-88a1-6045a7136220.PNG)

**Comment by AXAET** [comment]
这个UUID是iBeacon的ProximityUUID

**Comment by AXAET** [comment]
```
CLBeaconRegion *beaconRegion = [[CLBeaconRegion alloc] initWithProximityUUID:[[NSUUID alloc] initWithUUIDString:@"FDA50693-A4E2-4FB1-AFCF-C6EB07647825"] identifier:@"net.axaet.www"]；把这个ProximityUUID改成自己的试试
```

**Comment by wujx1992** [comment]
谢谢。我们服务端的开发人员告诉我不同的设备是不一样的 😒。显然他误导了我😭

**Comment by 15828881249** [comment]
不错
